### PR TITLE
Use "previous" icon instead of close button, separate buttons to prevent confusion

### PR DESCRIPTION
**Pull request by jeanthom**
I find the "Close" button inappropriate in the Pool Manager, I think that a "Previous" button would be more appropriate.

I also used different packing position to separate "Previous" action and "Update pool" action.

### CODE REVIEW

**Comment by carrotIndustries** [comment]
Replacing the "Close" button with a "back" one is definitely the right thing to do. I'll still have to make up my mind about the placement of the update button, but putting it to the left side probably fine too.

While you're at it, have a look at the project manager as well, the UI is pretty similar.

**Comment by carrotIndustries** [comment]
> but putting it to the left side probably fine too.

Oops I meant the right side. TBH, my judgment in that regard is rather limited since I stared at that window for way too long and initial placement went without much thought. What looks best to you?

**Comment by jeanthom** [comment]
I think seperating action buttons from navigation buttons when possible is a good idea, however this is a personnal preference, and I'm not a UX expert

**Comment by carrotIndustries** [comment]
I had a look at various gnome applications, they all have the non-navigation buttons on the right side, so putting the "update pool" button on the right side is the way to go.

**Comment by jeanthom** [comment]
Maybe we should merge this PR and then tacke interface uniformisation elsewhere ?

**Pull request merged**
