### PR TITLE
New selection filter, using .ui files for interface description

### PR DESCRIPTION
**Pull request by jeanthom**
Here is the new design :
capture d ecran_2018-02-08_01-11-45

What disturbed me in the previous design : the "select all" button icon wasn't explicit, the arrow right in front of each checkbox means to me that there was something to expand but no.
Regression : you cannot select ONE item anymore by clicking on a button. If that feature is really important, we could reimplement it.

### CODE REVIEW

**Comment by carrotIndustries** [comment]
> you cannot select ONE item anymore by clicking on a button. If that feature is really important, we could reimplement it.

That feature is really important to at least me, since selecting only one object type is a common use case.

Some more nitpicking:
 - Don't override font sizes and padding unless really needed
 - This dialog doesn't use header bars whereas every other dialog does
 - The listbox doesn't expand with the window
 - Your layout has has very little padding, doesn't look consistent with the rest of the application

Overall, only these aspects of the current implementation may need improvement:
 - Find another icon for the "select one" button
 - Move the "select all" button from the header bar to the main window

**Comment by jeanthom** [comment]
peek 08-02-2018 13-07

I can't get the window size to be wide enough so that the title is displayed correctly :frowning_face:

**Comment by jeanthom** [comment]
capture d ecran_2018-02-08_14-02-13

**Comment by carrotIndustries** [comment]
I'm not quite sure whether differentiating between the check mark and its label is a good idea from a usability POV, we should probably retain that extra button.

The padding thing wasn't referring to the padding around the scrolledwindow, but rather to the individual elemement's padding.

Having that large button in the doesn't look particularly pretty, so either find a more suitable icon or place the button inside the actual window.

**Comment by jeanthom** [comment]
> I'm not quite sure whether differentiating between the check mark and its label is a good idea from a usability POV, we should probably retain that extra button.

I agree on that point, but I can't find an icon that carries the right message. The current "select only" icon is more suited for folded content.

Also, is the selection filter really used that much to justify a button in the header bar ? Why not integrate the selection filter into the GtkPopover for selection settings ?

**Comment by atoav** [comment]
When doing multiple footprints for TSSOP yesterday I used this thing a lot in its old state. What I thought from a usability standpoint:  
- I think the whole thing could be in the left sidebar instead of a floating window. Typically this kind of modal window style used in Blender for example) helps to use screen space more effectively.
- I'd generally like to have the ability to click drag over multiple checkboxes (this would be great for all toggleable lists in horizon, like layer visibility etc). See the way photoshop did it:  
Photoshop layer selection

**Comment by jeanthom** [comment]
The click'n'drag won't be easy to implement, but it seems like the right thing to do.

**Comment by atoav** [comment]
@jeanthom I thought that it wouldn't be easy but it could be re-used more than once. Maybe one could ask the [guys at Blender](https://wiki.blender.org/index.php/Community:Chat) for pointers, because they have the same implemented in their Outliner:   
blender_drag_selection

**Comment by jeanthom** [comment]
Blender has their own interface toolkit, so we can't use their code unfortunately :-(

**Comment by carrotIndustries** [comment]
0ec5457883bf7bf25868ba0b4f0d21e3572d5573 does away with the arrow and changes the button for selecting all object types

**Pull request closed without merging**
