### PR TITLE
UI: Add coarse and fine keyboard movements

### PR DESCRIPTION
**Pull request by frmdstryr**
Adds the `mod` to ToolArgs key presses which can be used to distinguish between the different move modes (fine, default, coarse).  For #206 

The only todo is that the modifier binding isn't configurable, other than that it works quite nicely.

### CODE REVIEW

**Comment by carrotIndustries** [comment]
> perhaps it'd be better to generate actions based on the preferences?

I've though a bit about more about that and came up with that plan:

Having the key sequences for the "move keyboard" tools configurable is a bit silly. No one's going to change these and those who do will be wondering why things broke. To remove these from the preferences dialog, add a new flag `NO_PREFERENCES` to `ActionCatalogItem::Flags`, then set the key sequences for these tools depending on the users' preference for the fine modifier.

> I was thinking of re-checking for any matching key sequences to lookup the tool id, in
[`bool ImpBase::handle_key_press(GdkEventKey *key_event)`](https://github.com/carrotIndustries/horizon/blob/master/src/imp/imp.cpp#L1040) then assign the matching tool_id to the ToolArgs.

Since I can't yet think of a use case apart from the move tool, I'm not really convinced by this.

To know whether to do a fine movement in `ToolMove::update` figure out the modifiers in the imp and pass normal/fine to the tool.

**Comment by frmdstryr** [comment]
What about just doing this: https://github.com/carrotIndustries/horizon/compare/master...frmdstryr:move-tool

It works good enough, the only somewhat confusing thing is that the move tool must be activated first before a fine move can be done. It's reusing the `button` but it's probably better to add a new member to the ToolArgs. 

Or it may just be better for you to implement it however you think is best :+1: (feel free to just close this)

**Comment by carrotIndustries** [comment]
> It works good enough, the only somewhat confusing thing is that the move tool must be activated first before a fine move can be done.

That's not really what we want.

> Or it may just be better for you to implement it however you think is best +1 (feel free to just close this)

done in 3b12b58e34cb1b9fcbe97f4e6e624a4c895b09d6

Thanks for making me think a bit more about this issue!

**Comment by frmdstryr** [comment]
Works great! Thank you!

**Pull request closed without merging**
